spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
    username: root
    password: Wathsala@1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
<<<<<<< HEAD

=======
>>>>>>> 6bbc0d5a1f76b1dff0a01c38f96bef6ff89721fd
